FROM ghcr.io/Goojoe/gpt-load:latest

WORKDIR /app

# 健康检查
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:7860/health || exit 1


EXPOSE 7860

CMD ["./gpt-load"]