version: "3.8"

services:
  gpt-load:
    image: ghcr.io/tbphp/gpt-load:latest
    container_name: gpt-load
    ports:
      - "7860:7860"
    volumes:
      # 挂载密钥文件（只读）
      - ./keys.txt:/app/keys.txt:ro
      # 挂载配置文件（只读）
      - ./.env:/app/.env:ro
    restart: unless-stopped
    tty: true

    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    env_file:
      - .env
